# Generated by Django 3.2.12 on 2022-02-09 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cpu', models.SmallIntegerField(verbose_name='Количество ядер')),
                ('ram', models.SmallIntegerField(verbose_name='Объем ram')),
                ('hdd', models.SmallIntegerField(verbose_name='Объем hdd')),
                ('status', models.CharField(choices=[('started', 'started'), ('blocked', 'blocked'), ('stopped', 'stopped')], default='stopped', max_length=10, verbose_name='Статус сервера')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Объект VPS',
                'verbose_name_plural': 'Объекты VPS',
                'db_table': 'api_vps',
                'ordering': ('create_date',),
            },
        ),
    ]
